### ISSUE TITLE
`Microsoft.CodeAnalysis.Testing.Lightup.ProgrammaticSuppressionInfoWrapper` throws `TypeInitializationException`

### ISSUE THREAD

**Issue by foriequal0** [dotnet/roslyn-sdk#1175]
Microsoft.CodeAnalysis.Testing.Lightup.ProgrammaticSuppressionInfoWrapper throws TypeInitializationException when there are suppressed diagnostics, from `Microsoft.CodeAnalysis` version 4.10.0

It tries to make a property accessor of Roslyn's `ProgrammaticSuppressionInfo.Suppressions`.

It had a type `ImmutableHashSet<(string Id, LocalizableString Justification)>` before,
https://github.com/dotnet/roslyn/blob/db71ffa0e75bab0e69fad83259469cb471f1edbd/src/Compilers/Core/Portable/Diagnostic/ProgrammaticSuppressionInfo.cs#L15
but it's been changed to `ImmutableArray<Suppression>` after this PR https://github.com/dotnet/roslyn/pull/71207
https://github.com/dotnet/roslyn/blob/969c5177a3fe0a13171c561b45b2d808b9659e56/src/Compilers/Core/Portable/Diagnostic/ProgrammaticSuppressionInfo.cs#L16C16-L16C43

**Comment by roji** [comment]
We're also encountering this in EF core testing when trying to upgrade from Microsoft.CodeAnalysis 4.8.0 to 4.10.0 (see #34116).

**Comment by Herrmel** [comment]
@sharwell Can we expect an update for the nuget packages some time soon? This bug currently prevents me from updating my Microsoft.CodeAnalysis Packages.

**Comment by bradwilson** [comment]
Same, would be nice for a new package release for this so I can stop holding back package upgrades.

**Comment by bradwilson** [comment]
@sharwell As of today, that has become a critical blocker because the dependencies of 1.1.1 have security issues that break builds with the .NET 9 SDK:

```
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'Newtonsoft.Json' 9.0.1 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'NuGet.Common' 5.6.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-6qmf-mmc7-6c2p
xunit.analyzers.tests.csproj : error NU1904: Warning As Error: Package 'NuGet.Packaging' 5.6.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-68w7-72jg-6qpp
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'NuGet.Protocol' 5.6.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-6qmf-mmc7-6c2p
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'NuGet.Protocol' 5.6.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-g3q9-xf95-8hp5
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'System.Net.Http' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-7jgj-8wvc-jh57
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'System.Private.Uri' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-5f2m-466j-3848
xunit.analyzers.tests.csproj : error NU1902: Warning As Error: Package 'System.Private.Uri' 4.3.0 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-x5qj-9vmx-7g6g
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'System.Private.Uri' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-xhfc-gr8f-ffwc
xunit.analyzers.tests.csproj : error NU1903: Warning As Error: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

**Comment by bradwilson** [comment]
@sharwell Where are the instructions for how to use your pre-release pacakges?

**Comment by bradwilson** [comment]
ping @sharwell

**Comment by dellis1972** [comment]
Which version was this fix released in? 

I'm using the following package references which look to be all the latest but still get the following error

```
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.12.0-3.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.12.0-3.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing" Version="1.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0-3.final" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.12.0-3.final" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.12.0-3.final" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.12.0-3.final" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.12.0-3.final" GeneratePathProperty="true" />
  </ItemGroup>
```

```
System.TypeInitializationException : The type initializer for 'Microsoft.CodeAnalysis.Testing.Lightup.ProgrammaticSuppressionInfoWrapper' threw an exception.
  ----> System.InvalidOperationException : Property 'System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.Diagnostics.Suppression] Suppressions' produces a value of type 'System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.Diagnostics.Suppression]', which is not assignable to type 'System.Collections.Immutable.ImmutableHashSet`1[System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.LocalizableString]]'
   at Microsoft.CodeAnalysis.Testing.Lightup.ProgrammaticSuppressionInfoWrapper.FromInstance(Object instance) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Lightup/ProgrammaticSuppressionInfoWrapper.cs:line 32
   at Microsoft.CodeAnalysis.Testing.Extensions.DiagnosticExtensions.ProgrammaticSuppressionInfo(Diagnostic diagnostic) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Extensions/DiagnosticExtensions.cs:line 38
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<>c.<FilterDiagnostics>b__103_0(ValueTuple`2 d) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1687
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.FilterDiagnostics(ImmutableArray`1 diagnostics) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1686
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSortedDiagnosticsAsync(Solution solution, ImmutableArray`1 analyzers, ImmutableArray`1 additionalDiagnostics, CompilerDiagnostics compilerDiagnostics, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1144
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSortedDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, ImmutableArray`1 analyzers, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1090
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 449
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 203
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 172
   at CSharpSuppressorVerifier`2.VerifySuppressorAsync(String source, DiagnosticResult[] expected) in /Users/dean/Documents/Sandbox/Xamarin/android/src/Microsoft.Android.Sdk.Analysis/Tests/Verifiers/CSharpAnalyzerVerifier`1.cs:line 60
   at DNAS0001Tests.IDE0001IsSuppressed() in /Users/dean/Documents/Sandbox/Xamarin/android/src/Microsoft.Android.Sdk.Analysis/Tests/DNAS0001Tests.cs:line 56
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--InvalidOperationException
   at Microsoft.CodeAnalysis.Testing.Lightup.LightupHelpers.CreatePropertyAccessor[T,TResult](Type type, String propertyName, TResult defaultValue) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Lightup/LightupHelpers.cs:line 53
   at Microsoft.CodeAnalysis.Testing.Lightup.ProgrammaticSuppressionInfoWrapper..cctor() in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Lightup/ProgrammaticSuppressionInfoWrapper.cs:line 21

```

I am using the following code 

```csharp
using VerifyCSSuppressor = CSharpSuppressorVerifier <DNAS0001Tests.IDE0002AnalyserWrapper, ResourceDesignerDiagnosticSuppressor>;

[Test]
	public async Task IDE0001IsSuppressed ()
	{
		var expected = VerifyCSSuppressor.Diagnostic (new DiagnosticDescriptor ("IDE0002", "", "Name can be simplified", "", DiagnosticSeverity.Hidden, isEnabledByDefault: true)).WithSpan (11, 23, 11, 31).WithIsSuppressed (true);
		await VerifyCSSuppressor.VerifySuppressorAsync (brokenCode, expected);
	}

public static partial class CSharpSuppressorVerifier<TAnalyzer, TSuppressor>
	where TAnalyzer : DiagnosticAnalyzer, new ()
	where TSuppressor : DiagnosticSuppressor, new ()
{
	/// <inheritdoc cref="AnalyzerVerifier{TAnalyzer, TTest, TVerifier}.Diagnostic ()"/>
	public static DiagnosticResult Diagnostic ()
		=> CSharpAnalyzerVerifier<TAnalyzer, DefaultVerifier>.Diagnostic ();

	/// <inheritdoc cref="AnalyzerVerifier{TAnalyzer, TTest, TVerifier}.Diagnostic(string)"/>
	public static DiagnosticResult Diagnostic (string diagnosticId)
		=> CSharpAnalyzerVerifier<TAnalyzer, DefaultVerifier>.Diagnostic (diagnosticId);

	/// <inheritdoc cref="AnalyzerVerifier{TAnalyzer, TTest, TVerifier}.Diagnostic (DiagnosticDescriptor)"/>
	public static DiagnosticResult Diagnostic (DiagnosticDescriptor descriptor)
		=> CSharpAnalyzerVerifier<TAnalyzer, DefaultVerifier>.Diagnostic (descriptor);
	public static async Task VerifySuppressorAsync (string source, params DiagnosticResult[] expected)
	{
		var test = new Test {
			TestCode = source,
		};
		test.ExpectedDiagnostics.AddRange (expected);
		await test.RunAsync (CancellationToken.None);
	}

	public class Test : CSharpAnalyzerTest<TAnalyzer, DefaultVerifier>
	{
		protected override IEnumerable<DiagnosticAnalyzer> GetDiagnosticAnalyzers ()
			=> base.GetDiagnosticAnalyzers ().Concat (new[] { new TSuppressor () });
	}
}
```

I have to use a Wrapper class for the IDE0002 because it doesn't have a public analyzer I can use

```csharp
[DiagnosticAnalyzer(LanguageNames.CSharp)]
	// disable warnings as we are not actually creating a DiagnosticAnalyzer
#pragma warning disable RS1036 // Specify analyzer banned API enforcement setting
#pragma warning disable RS1025 // Configure generated code analysis
#pragma warning disable RS1026 // Enable concurrent execution
	public class IDE0002AnalyserWrapper : DiagnosticAnalyzer
	{
		DiagnosticAnalyzer analyzer;
		ImmutableArray<DiagnosticDescriptor> diagnostics;
		public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => diagnostics;

		public IDE0002AnalyserWrapper ()
		{
			var a = new AnalyzerFileReference (Path.GetFullPath ("Microsoft.CodeAnalysis.CSharp.Features.dll"), assemblyLoader: AssemblyLoader.Instance);
			foreach (var a1 in a.GetAnalyzers (LanguageNames.CSharp))
			{
				if (a1.SupportedDiagnostics.Any (x => x.Id == "IDE0002"))
				{
					analyzer = a1;
					diagnostics = ImmutableArray.Create (analyzer.SupportedDiagnostics.First(x => x.Id == "IDE0002"));
					break;
				}
			}
		}

		public override void Initialize (AnalysisContext context)
		{
			analyzer.Initialize (context);
		}
	}
#pragma warning restore RS1026
#pragma warning restore RS1025
#pragma warning restore RS1036 // Specify analyzer banned API enforcement settingX
```

**Comment by bradwilson** [comment]
@dellis1972 They haven't released a fixed version. I'm still waiting for information about where their CI packages live, since that appears to be the recommendation based on the fact that they don't seem to be able to release a fixed version.

**Comment by bradwilson** [comment]
For those who might've been waiting for @sharwell to provide the answer, I found the feed to get pre-release NuGet packages via another source. Add this to your NuGet config:

```xml
<configuration>
  <packageSources>
     <add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

I can verify that upgrading from `1.1.1` to `1.1.3-beta1.24423.1` has fixed the security issues.

You should also be aware, if you're writing suppressors, that they have also fixed the issue where suppressors used to remove the diagnostic from the diagnostics list rather than marking it as suppressed, so you may need to (re-)add expected diagnostics for the analyzer you're suppressing, marked with `.WithIsSuppressed(true)` in your tests. This was how it was previously working in Roslyn 3.11, but somewhere in the 4.x tree they broke it, and now it's back to the original behavior (which is better for testability, IMO).

**Comment by roji** [comment]
@sharwell @bradwilson in EF I took a dependency on Microsoft.CodeAnalysis.Analyzer.Testing 1.1.3-beta1.24423.1 as above, and I can also confirm that fixes the issue. But we also use Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit which only has 1.1.3-beta1.24352.1, which requires that same exact Microsoft.CodeAnalysis.Analyzer.Testing, resulting in a NU1608 for a bad dependency version. I suppressed that for now and the tests are running fine, but is that the expected state for now?

**Comment by bradwilson** [comment]
>  Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit

I have no relation to this library and don't recommend people use it. The generic Microsoft.CodeAnalysis.CSharp.Analyzer.Testing is what we use.

**Comment by roji** [comment]
Thanks @bradwilson - though that seems to be an official Roslyn package... Would you mind pointing me to a project where you test your analyzers/code fixes, so I can see how you do things?

**Comment by bradwilson** [comment]
@roji https://github.com/xunit/xunit.analyzers

**Comment by sharwell** [comment]
> Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit

This library is obsolete. The final version of this library we published produces build warnings saying the code should migrate to the generic one instead.

**Comment by JasonBock** [comment]
I just ran into this issue today using `1.1.2`. I realize I can grab the pre-release from the feed @bradwilson mentioned above, but is there any plan to release the fixed package to NuGet proper?
