### ISSUE TITLE
code fix test fails without showing any "visible" difference in diff output

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-sdk#876]
See build [here](https://github.com/Youssef1313/YAnalyzers/actions/runs/978044397) (PR: https://github.com/Youssef1313/YAnalyzers/pull/38).

It passes on Windows, but not Linux or macOS, which makes me feel like there is a line ending issue.

```
  Failed TestAddUsing [329 ms]
  Error Message:
   Assert.Fail failed. Context: Iterative code fix application
content of '/0/Test0.cs' did not match. Diff shown with expected as baseline:
 
 using System.Collections.Generic;
 using System.Linq;
 
 class C
 {
     public void M(string[] s)
     {
         List<string> x = s.ToList();
     }
 }
 

  Stack Trace:
     at Microsoft.CodeAnalysis.Testing.Verifiers.MSTestVerifier.Fail(String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.MSTest/MSTestVerifier.cs:line 78
   at Microsoft.CodeAnalysis.Testing.IVerifierExtensions.EqualOrDiff(IVerifier verifier, String expected, String actual, String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Extensions/IVerifierExtensions.cs:line 56
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.VerifyFixAsync(String language, ImmutableArray`1 analyzers, ImmutableArray`1 codeFixProviders, SolutionState oldState, SolutionState newState, Int32 numberOfIterations, Func`10 getFixedProject, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 415
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.VerifyFixAsync(SolutionState testState, SolutionState fixedState, SolutionState batchFixedState, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 372
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 248
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 180
   at YAnalyzers.Test.CSharpCodeFixVerifier`2.VerifyCodeFixAsync(String source, DiagnosticResult[] expected, String fixedSource) in /home/runner/work/YAnalyzers/YAnalyzers/src/UnitTests/Verifiers/CSharpCodeFixVerifier`2.cs:line 58
   at YAnalyzers.Test.CSharpCodeFixVerifier`2.VerifyCodeFixAsync(String source, DiagnosticResult expected, String fixedSource) in /home/runner/work/YAnalyzers/YAnalyzers/src/UnitTests/Verifiers/CSharpCodeFixVerifier`2.cs:line 46
   at YAnalyzers.Test.UseImplicitOrExplicitTypeAnalyzerTests.TestAddUsing() in /home/runner/work/YAnalyzers/YAnalyzers/src/UnitTests/UseImplicitOrExplicitTypeAnalyzerTests.cs:line 482
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

@sharwell Can you help here? Thanks!

**Comment by sharwell** [comment]
Yes, this is a line ending issue. For dotnet/roslyn-sdk, we really just need to update `EqualOrDiff` to have special rendering for lines that differ by line ending, but I'm not sure what the best way to implement this is.

**Comment by Youssef1313** [comment]
I think in the case of line ending difference, it's easiest to print the expected and the actual results as a single line containing `\r\n` or '\n`s.

I can't think of a good way to render the EOL differences as a diff.

In case there are other changes than only line endings, I'd prefer the current behavior (showing a diff), i.e, only show the full expected and full actual strings if there is **only** EOL differences. What do you think?

**Comment by sharwell** [comment]
Beyond Compare renders CRLF as `¤` and LF as `¶`. I've also seen cases where CR is rendered as `<CR>` and LF is rendered as `<LF>` (with both showing as `<CR><LF>`). Either of these approaches would be visible for the mixed line endings case, but I'm guessing the noise would only be desired if the _only_ changes present are EOL changes.

**Comment by Youssef1313** [comment]
Thanks for the very quick fix @sharwell!
